<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.bhojanalay</groupId>
    <artifactId>bhojanalay-nivas</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>backend/common-lib</module>
        <module>backend/discovery-service</module>
        <module>backend/restaurant-service</module>
        <module>backend/order-service</module>
        <module>backend/payment-service</module>
        <module>backend/api-gateway</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.5.4</spring.boot.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
    </properties>

</project>