spring.application.name=api-gateway
server.port=8080

# Configuration for Eureka client
#spring.cloud.gateway.mvc.routes.id=auth-service
#spring.cloud.gateway.mvc.routes.uri=lb://AUTH-SERVICE
#spring.cloud.gateway.mvc.routes.predicates[0]=Path=/api/v1/auth/**

# Configuration for Config Server
spring.config.import=optional:configserver:http://localhost:8888