spring.application.name=config-server
server.port=8888

profile.active=dev

#Configuration for config server
spring.cloud.config.server.git.uri=https://github.com/saurabh23patre93/bhojanalay-nivas.git
spring.cloud.config.server.git.default-label=develop
spring.cloud.config.server.git.search-paths=bhojanalay-config-repo
spring.cloud.config.server.git.clone-on-start=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
spring.cloud.config.server.bootstrap=false
